### ISSUE TITLE
Advance example undefined "Optional[BaseRoom] = None"

### ISSUE THREAD

**Issue by dariush-saberi** [yoelbassin/Websocket-Rooms#3]
Hi, I cannot figure out this part Optional[BaseRoom] = None in the advanced example. I get 
`

> NameError: name 'BaseRoom' is not defined

`

May you please check. Thanks

**Comment by yoelbassin** [comment]
Hey Durish!
Thank you for reporting this issue.
During development I considered using the `BaseRoom` object but later decided to remove it.
It looks like this doc hasn't been updated since.
I'll look into it today and hope it will be fixed within the next few hours so the doc will be up to date.
Thanks again, I really appreciate your report.

**Comment by dariush-saberi** [comment]
Thank you .. waiting for it.

**Comment by yoelbassin** [comment]
Hey!
I've updated the README file and it should be up to date now.
Thanks again!

**Comment by dariush-saberi** [comment]
This is working now, thanks. I would appreciate if you could add an advanced example of a Room ID. I think getting the Room participants is quite straightforward, but defining a Room ID is crucial for, say, social media chat rooms.

**Comment by dariush-saberi** [comment]
Thank you it works now.

**Comment by dariush-saberi** [comment]
However, there is one important feature missing, I guess. I tried to assign a Room ID but it did not work. Any idea on how to assign room ids?

**Comment by yoelbassin** [comment]
For having rooms with Id's you might want to do something like this: 
_(Note: this example uses `fastapi` but you might use something else)_
```python
app = FastAPI()


class RoomWithIdClientId(Room):
    def __init__(self, id: str) -> None:
        super().__init__()
        self._id_to_ws = {}

        self._id = id

    async def connect(self, websocket: WebSocket, client_id: int) -> None:
        self._id_to_ws[websocket] = client_id
        await super().connect(websocket)

    def get_client_id(self, websocket: WebSocket) -> int:
        return self._id_to_ws.get(websocket)

    @property
    def id(self) -> str:
        return self._id


def chat_room_factory(id: str) -> Room:
    _room = RoomWithIdClientId(id)

    @_room.on_receive("text")
    async def on_chatroom_receive(
        room: RoomWithIdClientId, websocket: WebSocket, message: Any
    ) -> None:
        await room.push_json(
            f"{room.id} - {room.get_client_id(websocket)}: '{message}'"
        )

    @_room.on_connect("before")
    async def before_chatroom_connection(
        room: RoomWithIdClientId, websocket: WebSocket
    ) -> None:
        await room.push_json(
            f"{room.id} - {room.get_client_id(websocket)} is about to join the room!"
        )

    @_room.on_connect("after")
    async def after_chatroom_connection(
        room: RoomWithIdClientId, websocket: WebSocket
    ) -> None:
        await room.push_json(
            f"{room.id} - {room.get_client_id(websocket)} has joined the chat room!"
        )

    return _room


rooms = [chat_room_factory(i) for i in range(10)]


def all_rooms():
    return rooms


@app.websocket("/chat_rooms/{id}/{client_id}")
async def connect_websocket(
    websocket: WebSocket,
    id: int,
    client_id: int,
    all_rooms: List[RoomWithIdClientId] = Depends(all_rooms),
):
    if id >= len(all_rooms):
        raise ValueError(f"Room {id} does not exist")
    await all_rooms[id].connect(websocket, client_id)
```

Please don't hesitate to write if you have any more questions regarding this project!

**Comment by dariush-saberi** [comment]
Great. Thank you. I will run the code and I will get back to you in case of queries.
